### ISSUE TITLE
setup.cfg: no escaped character

### ISSUE THREAD

**Issue by Broam** [rm-you/ninjalooter#5]
Line 20 of setup.cfg bugs out when running `tox` on Ubuntu 20.04

I was able to work around this by changing the backslash to a forward slash.

    data = data\\*
    data = data/*

Log follows:

brian@Cy:~/src/ninjalooter$ tox -e pep8,pylint,coverage
pep8 create: /home/brian/src/ninjalooter/.tox/pep8
pep8 installdeps: -r/home/brian/src/ninjalooter/requirements.txt, -r/home/brian/src/ninjalooter/test-requirements.txt
pep8 develop-inst: /home/brian/src/ninjalooter
ERROR: invocation failed (exit code 1), logfile: /home/brian/src/ninjalooter/.tox/pep8/log/pep8-2.log
==================================================================================================== log start ====================================================================================================
Obtaining file:///home/brian/src/ninjalooter
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [28 lines of output]
      /home/brian/src/ninjalooter/.tox/pep8/lib/python3.8/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      Error parsing
      Traceback (most recent call last):
        File "/home/brian/src/ninjalooter/.eggs/pbr-5.8.1-py3.8.egg/pbr/core.py", line 111, in pbr
          attrs = util.cfg_to_args(path, dist.script_args)
        File "/home/brian/src/ninjalooter/.eggs/pbr-5.8.1-py3.8.egg/pbr/util.py", line 272, in cfg_to_args
          pbr.hooks.setup_hook(config)
        File "/home/brian/src/ninjalooter/.eggs/pbr-5.8.1-py3.8.egg/pbr/hooks/__init__.py", line 28, in setup_hook
          files.FilesConfig(config, metadata_config.get_name()).run()
        File "/home/brian/src/ninjalooter/.eggs/pbr-5.8.1-py3.8.egg/pbr/hooks/base.py", line 27, in run
          self.hook()
        File "/home/brian/src/ninjalooter/.eggs/pbr-5.8.1-py3.8.egg/pbr/hooks/files.py", line 118, in hook
          self.expand_globs()
        File "/home/brian/src/ninjalooter/.eggs/pbr-5.8.1-py3.8.egg/pbr/hooks/files.py", line 76, in expand_globs
          unquoted_prefix = unquote_path(source_prefix)
        File "/home/brian/src/ninjalooter/.eggs/pbr-5.8.1-py3.8.egg/pbr/hooks/files.py", line 51, in unquote_path
          return "".join(shlex.split(path))
        File "/usr/lib/python3.8/shlex.py", line 311, in split
          return list(lex)
        File "/usr/lib/python3.8/shlex.py", line 300, in __next__
          token = self.get_token()
        File "/usr/lib/python3.8/shlex.py", line 109, in get_token
          raw = self.read_token()
        File "/usr/lib/python3.8/shlex.py", line 210, in read_token
          raise ValueError("No escaped character")
      ValueError: No escaped character
      error in setup command: Error parsing /home/brian/src/ninjalooter/setup.cfg: ValueError: No escaped character
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

===================================================================================================== log end =====================================================================================================
/home/brian/src/ninjalooter/.tox/pep8/lib/python3.8/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
  warnings.warn(
Error parsing
Traceback (most recent call last):
  File "/home/brian/src/ninjalooter/.eggs/pbr-5.8.1-py3.8.egg/pbr/core.py", line 111, in pbr
    attrs = util.cfg_to_args(path, dist.script_args)
  File "/home/brian/src/ninjalooter/.eggs/pbr-5.8.1-py3.8.egg/pbr/util.py", line 272, in cfg_to_args
    pbr.hooks.setup_hook(config)
  File "/home/brian/src/ninjalooter/.eggs/pbr-5.8.1-py3.8.egg/pbr/hooks/__init__.py", line 28, in setup_hook
    files.FilesConfig(config, metadata_config.get_name()).run()
  File "/home/brian/src/ninjalooter/.eggs/pbr-5.8.1-py3.8.egg/pbr/hooks/base.py", line 27, in run
    self.hook()
  File "/home/brian/src/ninjalooter/.eggs/pbr-5.8.1-py3.8.egg/pbr/hooks/files.py", line 118, in hook
    self.expand_globs()
  File "/home/brian/src/ninjalooter/.eggs/pbr-5.8.1-py3.8.egg/pbr/hooks/files.py", line 76, in expand_globs
    unquoted_prefix = unquote_path(source_prefix)
  File "/home/brian/src/ninjalooter/.eggs/pbr-5.8.1-py3.8.egg/pbr/hooks/files.py", line 51, in unquote_path
    return "".join(shlex.split(path))
  File "/usr/lib/python3.8/shlex.py", line 311, in split
    return list(lex)
  File "/usr/lib/python3.8/shlex.py", line 300, in __next__
    token = self.get_token()
  File "/usr/lib/python3.8/shlex.py", line 109, in get_token
    raw = self.read_token()
  File "/usr/lib/python3.8/shlex.py", line 210, in read_token
    raise ValueError("No escaped character")
ValueError: No escaped character
error in setup command: Error parsing /home/brian/src/ninjalooter/setup.cfg: ValueError: No escaped character
ERROR: invocation failed (exit code 1)
/home/brian/src/ninjalooter/.tox/pep8/lib/python3.8/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
  warnings.warn(
Error parsing
Traceback (most recent call last):
  File "/home/brian/src/ninjalooter/.eggs/pbr-5.8.1-py3.8.egg/pbr/core.py", line 111, in pbr
    attrs = util.cfg_to_args(path, dist.script_args)
  File "/home/brian/src/ninjalooter/.eggs/pbr-5.8.1-py3.8.egg/pbr/util.py", line 272, in cfg_to_args
    pbr.hooks.setup_hook(config)
  File "/home/brian/src/ninjalooter/.eggs/pbr-5.8.1-py3.8.egg/pbr/hooks/__init__.py", line 28, in setup_hook
    files.FilesConfig(config, metadata_config.get_name()).run()
  File "/home/brian/src/ninjalooter/.eggs/pbr-5.8.1-py3.8.egg/pbr/hooks/base.py", line 27, in run
    self.hook()
  File "/home/brian/src/ninjalooter/.eggs/pbr-5.8.1-py3.8.egg/pbr/hooks/files.py", line 118, in hook
    self.expand_globs()
  File "/home/brian/src/ninjalooter/.eggs/pbr-5.8.1-py3.8.egg/pbr/hooks/files.py", line 76, in expand_globs
    unquoted_prefix = unquote_path(source_prefix)
  File "/home/brian/src/ninjalooter/.eggs/pbr-5.8.1-py3.8.egg/pbr/hooks/files.py", line 51, in unquote_path
    return "".join(shlex.split(path))
  File "/usr/lib/python3.8/shlex.py", line 311, in split
    return list(lex)
  File "/usr/lib/python3.8/shlex.py", line 300, in __next__
    token = self.get_token()
  File "/usr/lib/python3.8/shlex.py", line 109, in get_token
    raw = self.read_token()
  File "/usr/lib/python3.8/shlex.py", line 210, in read_token
    raise ValueError("No escaped character")
ValueError: No escaped character
error in setup command: Error parsing /home/brian/src/ninjalooter/setup.cfg: ValueError: No escaped character
ERROR: invocation failed (exit code 1)
_____________________________________________________________________________________________________ summary _____________________________________________________________________________________________________
ERROR:   pep8: InvocationError for command /home/brian/src/ninjalooter/.tox/pep8/bin/python -m pip install --exists-action w -e . (exited with code 1)
ERROR:   pylint: InvocationError for command /home/brian/src/ninjalooter/.tox/pep8/bin/python setup.py --name (exited with code 1)
ERROR:   coverage: InvocationError for command /home/brian/src/ninjalooter/.tox/pep8/bin/python setup.py --name (exited with code 1)

**Comment by rm-you** [comment]
Closing this issue as it should be resolved with commit c6913a4 👍
